name       : cifs-utils
version    : '6.13'
release    : 8
source     :
    - https://www.samba.org/ftp/linux-cifs/cifs-utils/cifs-utils-6.13.tar.bz2 : 43d8786c8613caccfa84913081c1d62bc2409575854cf895b05b48af0863d056
license    : GPL-3.0-only
component  : network.utils
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(talloc)
    - python-docutils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
