name       : cifs-utils
version    : '6.15'
release    : 11
source     :
    - https://www.samba.org/ftp/linux-cifs/cifs-utils/cifs-utils-6.15.tar.bz2 : a7b6940e93250c1676a6fa66b6ead91b78cd43a5fee99cc462459c8b9cf1e6f4
license    : GPL-3.0-only
component  : network.utils
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(talloc)
    - python-docutils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
