name       : cifs-utils
version    : '6.14'
release    : 10
source     :
    - https://www.samba.org/ftp/linux-cifs/cifs-utils/cifs-utils-6.14.tar.bz2 : 6609e8074b5421295ff012a31f02ccd9a058415c619c81362ebb788dbf0756b8
license    : GPL-3.0-only
component  : network.utils
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(talloc)
    - python-docutils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
