name       : cifs-utils
version    : '6.10'
release    : 6
source     :
    - https://www.samba.org/ftp/linux-cifs/cifs-utils/cifs-utils-6.10.tar.bz2 : 92fc29c8e9039637f3344267500f1fa381e2cccd7d10142f0c1676fa575904a7
license    : GPL-3.0-only
component  : network.utils
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(talloc)
    - python-docutils
setup      : |
    %patch -p1 < $pkgfiles/append-destdir-to-makefile.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
