name       : cifs-utils
version    : 6.8
release    : 5
source     :
    - https://ftp.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.8.tar.bz2 : e7d1f6050c43f21f82cd77e288eb756755effd22f0c310fc2c525df9d41dff79
license    : GPL-3.0-only
component  : network.utils
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
    - pkgconfig(libcap-ng)
    - pkgconfig(talloc)
    - python-docutils
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
