name       : cifs-utils
version    : 6.4
release    : 2
source     :
    - https://ftp.samba.org/pub/linux-cifs/cifs-utils/cifs-utils-6.4.tar.bz2 : 38fc63926af435dae4ebcf4406275580a692d9fb9ee3e32170317cf2ba68e6e3
license    : GPL-3.0
summary    : CIFS Filesystem Utilities
description: |
    Utilities for doing and managing mounts of the Linux CIFS filesystem.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
